vich_uploader:
    db_driver: orm

    mappings:
        blog_post_images:
            uri_prefix: /images/blog_post_images
            upload_destination: '%kernel.project_dir%/public/images/blog_post_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
